"""add two new columns to the users table

Revision ID: 764edf8beb79
Revises: 2d842e3fbc15
Create Date: 2018-11-25 17:46:47.830821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764edf8beb79'
down_revision = '2d842e3fbc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
