"""update both user and blog models

Revision ID: b3eef53e0522
Revises: 3bba21eab12f
Create Date: 2018-11-27 22:26:49.203777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3eef53e0522'
down_revision = '3bba21eab12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_blog_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_blog_id_fkey', 'users', 'blogs', ['blog_id'], ['id'])
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###
