"""update both user and blog models

Revision ID: eda8fa199eed
Revises: 67ddc453032f
Create Date: 2018-11-27 23:54:13.288435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda8fa199eed'
down_revision = '67ddc453032f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date_of_blog', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'date_of_blog')
    # ### end Alembic commands ###
